+`{*.sh,hooks/*-*}:SUSUWU_INCLUDE()`; improves
	error messages about includes.

@`{*.sh,hooks/*-*}:GIT_ROOT`; ["Quote this to prevent word splitting"](https://www.shellcheck.net/wiki/SC2046) fix.

diff --git a/hooks/post-checkout b/hooks/post-checkout
--- a/hooks/post-checkout
+++ b/hooks/post-checkout
@@ -2,8 +2,18 @@
 #
 # This is [custom `post-checkout`](https://github.com/SwuduSusuwu/SusuLib/blob/preview/hooks/post-checkout):
 # Produces `./tags` [for `vim`](../README.md#purposes), uses `SUSUWU_LOCAL_WORKSPACE_JSON` [for local `compile_commands.json` tools](../README.md#purposes).
-GIT_ROOT="$(dirname $(git rev-parse --git-dir))/" #/* `git` does not set `${GIT_DIR}`, nor `${GIT_WORK_TREE}`. */
-. "${GIT_ROOT}/sh/make.sh" #/* SUSUWU_BUILD_CTAGS() SUSUWU_LOCAL_WORKSPACE_JSON() */
+GIT_ROOT="$(dirname "$(git rev-parse --git-dir)")/" #/* `git` does not set `${GIT_DIR}`, nor `${GIT_WORK_TREE}`. */
+SUSUWU_INCLUDE_ERROR() { #/* Usage; `SUSUWU_INCLUDE_ERROR "<relative path>" "error message"` */
+		echo "[$0: Error: \`GIT_WORK_TREE=${GIT_ROOT}\` \`\${GIT_WORK_TREE}${1}\` ${2}.]"; exit 1
+}
+SUSUWU_INCLUDE() { #/* Usage; `SUSUWU_INCLUDE "<relative path>"` */
+	if [ ! -e "${GIT_ROOT}${1}" ]; then
+		SUSUWU_INCLUDE_ERROR "${1}" "not found"
+	elif [ ! -x "${GIT_ROOT}${1}" ] || ! . "${GIT_ROOT}${1}"; then
+		SUSUWU_INCLUDE_ERROR "${1}" "not executable"
+	fi
+}
+SUSUWU_INCLUDE "${GIT_ROOT}/sh/make.sh" #/* SUSUWU_BUILD_CTAGS() SUSUWU_LOCAL_WORKSPACE_JSON() */
 STATUS_CODE=$?
 SUSUWU_LOCAL_WORKSPACE_JSON #/* Replace `${{ github.workspace }}` with `$(pwd)` */
 SUSUWU_BUILD_CTAGS 2>/dev/null #/* Produce `./tags` */
diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -2,8 +2,18 @@
 #
 # This is [custom `pre-commit`](https://github.com/SwuduSusuwu/SusuLib/blob/preview/hooks/pre-commit):
 # Produces `./tags` [for `vim`](../README.md#purposes), updates `./compile_commands.json` [for `clang-tidy`](../README.md#purposes), calls [sample `pre-commit` (which scans for non-ASCII filenames, conflict markers or whitespace errors)](../.git/hooks/pre-commit.sample)
-GIT_ROOT="$(dirname $(git rev-parse --git-dir))/" # `git` does not set `${GIT_DIR}`, nor `${GIT_WORK_TREE}`
-. "${GIT_ROOT}/sh/make.sh" || exit $? #/* SUSUWU_BUILD_CTAGS() SUSUWU_COMPILE_JSON_PATH_ SUSUWU_GITHUB_WORKSPACE_JSON() SUSUWU_IS_PREVIEW() */
+GIT_ROOT="$(dirname "$(git rev-parse --git-dir)")/" # `git` does not set `${GIT_DIR}`, nor `${GIT_WORK_TREE}`
+SUSUWU_INCLUDE_ERROR() { #/* Usage; `SUSUWU_INCLUDE_ERROR "<relative path>" "error message"` */
+		echo "[$0: Error: \`GIT_WORK_TREE=${GIT_ROOT}\` \`\${GIT_WORK_TREE}${1}\` ${2}.]"; exit 1
+}
+SUSUWU_INCLUDE() { #/* Usage; `SUSUWU_INCLUDE "<relative path>"` */
+	if [ ! -e "${GIT_ROOT}${1}" ]; then
+		SUSUWU_INCLUDE_ERROR "${1}" "not found"
+	elif [ ! -x "${GIT_ROOT}${1}" ] || ! . "${GIT_ROOT}${1}"; then
+		SUSUWU_INCLUDE_ERROR "${1}" "not executable"
+	fi
+}
+SUSUWU_INCLUDE "${GIT_ROOT}/sh/make.sh" || exit $? #/* SUSUWU_BUILD_CTAGS() SUSUWU_COMPILE_JSON_PATH_ SUSUWU_GITHUB_WORKSPACE_JSON() SUSUWU_IS_PREVIEW() */
 SUSUWU_GITHUB_WORKSPACE_JSON && git add "${SUSUWU_COMPILE_JSON_PATH_}" #/* Replace `$(pwd)` with `${{ github.workspace }}` for `compile_commands.json` */
 
 if SUSUWU_IS_PREVIEW; then #/* If `./tags` is tracked; */
diff --git a/hooks/prepare-commit-msg b/hooks/prepare-commit-msg
--- a/hooks/prepare-commit-msg
+++ b/hooks/prepare-commit-msg
@@ -3,8 +3,18 @@
 # This is [custom `prepare-commit-msg`](https://github.com/SwuduSusuwu/SusuLib/blob/preview/hooks/prepare-commit-msg):
 # Produces `./tags` [for `vim`](../README.md#purposes), restores metadata to prevent "error: cannot rebase: You have unstaged changes.".
 # TODO: to prevent [race conditions](https://wikipedia.org/wiki/Race_condition), execute more soon.
-GIT_ROOT="$(dirname $(git rev-parse --git-dir))/" # `git` does not set `${GIT_DIR}`, nor `${GIT_WORK_TREE}`
-. "${GIT_ROOT}/sh/make.sh" #/* SUSUWU_BUILD_CTAGS() SUSUWU_GITHUB_WORKSPACE_JSON() */ # . "${GIT_ROOT}/sh/Macros.sh" #/* SUSUWU_IS_PREVIEW() */
+GIT_ROOT="$(dirname "$(git rev-parse --git-dir)")/" # `git` does not set `${GIT_DIR}`, nor `${GIT_WORK_TREE}`
+SUSUWU_INCLUDE_ERROR() { #/* Usage; `SUSUWU_INCLUDE_ERROR "<relative path>" "error message"` */
+		echo "[$0: Error: \`GIT_WORK_TREE=${GIT_ROOT}\` \`\${GIT_WORK_TREE}${1}\` ${2}.]"; exit 1
+}
+SUSUWU_INCLUDE() { #/* Usage; `SUSUWU_INCLUDE "<relative path>"` */
+	if [ ! -e "${GIT_ROOT}${1}" ]; then
+		SUSUWU_INCLUDE_ERROR "${1}" "not found"
+	elif [ ! -x "${GIT_ROOT}${1}" ] || ! . "${GIT_ROOT}${1}"; then
+		SUSUWU_INCLUDE_ERROR "${1}" "not executable"
+	fi
+}
+SUSUWU_INCLUDE "${GIT_ROOT}/sh/make.sh" #/* SUSUWU_BUILD_CTAGS() SUSUWU_GITHUB_WORKSPACE_JSON() */ # . "${GIT_ROOT}/sh/Macros.sh" #/* SUSUWU_IS_PREVIEW() */
 STATUS_CODE=$?
 #git restore "${GIT_ROOT}/compile_commands.json" 2>/dev/null
 SUSUWU_GITHUB_WORKSPACE_JSON #/* Replace `$(pwd)` with `${{ github.workspace }}` for `compile_commands.json` */
