@`*.sh:SUSUWU_INCLUDE_ERROR()`; fix indent amount
Is followup to: commit 896b108354d3d226985b9cf339162f489ac7e5be (+`{*.sh,hooks/*-*}:SUSUWU_INCLUDE()`; improves), which introduced this.

diff --git a/hooks/prepare-commit-msg b/hooks/prepare-commit-msg
--- a/hooks/prepare-commit-msg
+++ b/hooks/prepare-commit-msg
@@ -5,7 +5,7 @@
 # TODO: to prevent [race conditions](https://wikipedia.org/wiki/Race_condition), execute more soon.
 GIT_ROOT="$(dirname "$(git rev-parse --git-dir)")/" # `git` does not set `${GIT_DIR}`, nor `${GIT_WORK_TREE}`
 SUSUWU_INCLUDE_ERROR() { #/* Usage; `SUSUWU_INCLUDE_ERROR "<relative path>" "error message"` */
-		echo "[$0: Error: \`GIT_WORK_TREE=${GIT_ROOT}\` \`\${GIT_WORK_TREE}${1}\` ${2}.]"; exit 1
+	echo "[$0: Error: \`GIT_WORK_TREE=${GIT_ROOT}\` \`\${GIT_WORK_TREE}${1}\` ${2}.]"; exit 1
 }
 SUSUWU_INCLUDE() { #/* Usage; `SUSUWU_INCLUDE "<relative path>"` */
 	SUSUWU_INCLUDE_PATH=${1}; shift #/* So path is not included in source'd scripts `$@` and `$*`. */
